# vim:fileencoding=utf-8

include alabaster-dark.conf

font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11

enable_audio_bell no
tab_title_template "{index}: {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
background_opacity 1
macos_option_as_alt yes
allow_remote_control yes

map ctrl+alt+b goto_tab -1
map ctrl+alt+0 goto_tab -1

map kitty_mod+alt+t goto_layout tall
map kitty_mod+alt+s goto_layout stack
map kitty_mod+alt+h goto_layout vertical
map kitty_mod+alt+v goto_layout horizontal
map kitty_mod+alt+g goto_layout grid
map kitty_mod+p last_used_layout
map kitty_mod+z toggle_layout stack

map kitty_mod+equal  change_font_size all +.5
map kitty_mod+plus   change_font_size all +.5
map kitty_mod+minus  change_font_size all -.5

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t     new_tab_with_cwd
map ctrl+shift+n     new_os_window_with_cwd

map alt+shift+[ previous_tab
map alt+shift+] next_tab
map alt+shift+h previous_window
map alt+shift+l next_window

map ctrl+shift+f2 detach_window
map ctrl+shift+f3 detach_window new-tab
map ctrl+shift+f4 detach_window ask

map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 9
