- hosts: localhost
  connection: local
  roles:
    - { role: golang, tags: ['golang'] }
    - { role: rust, tags: ['rust'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: dev-tools, tags: ['dev-tools'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: helix, tags: ['helix'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: fish, tags: ['fish'] }
    - { role: i3, tags: ['i3'] }
    - { role: mako, tags: ['mako'] }
    - { role: kanshi, tags: ['kanshi'] }
    - { role: sway, tags: ['sway'] }
    - { role: repos, tags: ['repos'] }
    - { role: docker, tags: ['docker'] }
    - { role: flatpaks, tags: ['flatpaks'] }
    - { role: passage, tags: ['passage'] }
    - { role: ssh, tags: ['ssh'] }
