- name: Check if rustup is installed
  command: which rustup
  register: rustup_check
  failed_when: false
  changed_when: false

- name: Install rustup and cargo
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: rustup_check.rc != 0

- name: Ensure cargo bin dir is in PATH for subsequent tasks
  set_fact:
    ansible_env_path: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
  when: "ansible_facts['env']['HOME'] ~ '/.cargo/bin' not in ansible_facts['env']['PATH']"
