dev_tools_packages:
  - git-delta
  - ripgrep
  - zoxide
  - fd
  - bat
  - broot
  - gdb
  - quickemu
  - lima
  - just
  - cargo-binstall
  - yq
  - hashicorp/tap/terraform
dev_tools_brew_taps:
  - hashicorp/tap
  - quickemu-project/quickemu
dev_tools_brew_casks:
  - hashicorp/tap/hashicorp-vagrant
  - codex
  - signal
  - kitty
dev_tools_vagrant_plugins:
  - vagrant-qemu
dev_tools_cargo_packages:
  - git-delta
  - tree-sitter-cli
  - cargo-nextest
