fd_package_name: 
dev_tools_packages:
  - ripgrep
  - zoxide
  - fd-find
  - bat
  - gdb
  - quickemu
  - just
  - protobuf-compiler
  - yq
  - gcc-c++
  - llvm
  - llvm-devel 
  - clang 
  - clang-devel 
  - clang-tools-extra 
  - lldb
  - python3-pip
  - kitty
  - lshw
  - lshw-gui
  - NetworkManager-tui
  - pavucontrol
  - btop
  - ninja-build
  - awscli2
  - nmap
  - hping3
  - entr
  - podman-compose
dev_tools_cargo_packages:
  - [git-delta, delta]
  - [tree-sitter-cli, tree-sitter]
  - [broot, broot]
  - [cargo-nextest, cargo-nextest]
  - [jwt-cli, jwt]
  - [watchexec-cli, watchexec]
  - [bacon, bacon]
