fd_package_name: fd-find
dev_tools_packages:
  - ripgrep
  - zoxide
  - "{{ fd_package_name }}"
  - bat
  - gdb
  - quickemu
  - just
  - protobuf-compiler
dev_tools_cargo_packages:
  - git-delta
  - tree-sitter-cli
  - broot
  - cargo-nextest
  - cargo-binstall
