fd_package_name: 
dev_tools_packages:
  - ripgrep
  - zoxide
  - fd-find
  - bat
  - gdb
  - quickemu
  - just
  - protobuf-compiler
  - yq
dev_tools_cargo_packages:
  - git-delta
  - tree-sitter-cli
  - broot
  - cargo-nextest
  - cargo-binstall
