- set_fact:
    config_dir: "{{ ansible_facts['env']['HOME'] }}/.config/kitty"
    kitty_font_size: "{{ 14 if ansible_facts['system'] == 'Darwin' else 11 }}"

- name: ensure config dir exists
  file:
    path: "{{ config_dir }}"
    state: directory

- name: template kitty config
  template:
    src: kitty.conf.j2
    dest: "{{ config_dir }}/kitty.conf"
    variable_start_string: "[["
    variable_end_string: "]]"

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
  loop:
    - diff.conf
    - dracula.conf
    - alabaster.conf
    - alabaster-dark.conf
