- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
  when: not homebrew_check.stat.exists
