- set_fact:
    desktop_backgrounds: "{{ ansible_facts['env']['HOME'] }}/Pictures/desktop-backgrounds"
    src_dir: "{{ ansible_facts['env']['HOME'] }}/src"

- name: checkout desktop pictures
  git:
    repo: git@github.com:joebb97/desktop-backgrounds.git
    dest: "{{ desktop_backgrounds }}"

- name: all pictures dir exists
  stat:
    path: "{{ desktop_backgrounds }}/all-pictures"
  register: pictures_stat

- name: run add all pictures
  shell: "{{ desktop_backgrounds }}/add-all-pictures.sh"
  args:
    chdir: "{{ desktop_backgrounds }}"
  when: not pictures_stat.stat.exists

- name: checkout personal repos
  git:
    repo: "git@github.com:joebb97/{{ item }}.git"
    dest: "{{ src_dir }}/{{ item }}"
    update: false
  loop:
    - homelab
    - sandbox

- name: checkout oss repos
  git:
    repo: "git@github.com:{{ item }}.git"
    dest: "{{ src_dir }}/oss/{{ item }}"
    update: false
  loop:
    - linkerd/linkerd2-proxy
    - linkerd/dev
    - tokio-rs/tokio
    - tokio-rs/axum
    - tokio-rs/mio
    - smol-rs/smol
    - smol-rs/polling
    - smol-rs/async-io
    - smol-rs/async-net
    - hyperium/hyper
    - memorysafety/river
    - vicanso/pingap
    - cloudflare/pingora
    - cloudflare/foundations
    - cloudflare/workers-rs
    - cloudflare/quiche
    - uNetworking/uWebSockets
    - uNetworking/uSockets
    - litespeedtech/lsquic
    - aws/s2n-quic
    - libuv/libuv
