- set_fact:
    config_dir: "{{ ansible_facts['env']['HOME'] }}/.config/i3"
    status_dir: "{{ ansible_facts['env']['HOME'] }}/.config/i3status"

- name: ensure config dir exists
  file:
    path: "{{ config_dir }}"
    state: directory

- name: copy config
  copy:
    src: config
    dest: "{{ config_dir }}/config"

- name: ensure status dir exists
  file:
    path: "{{ status_dir }}"
    state: directory
- name: copy status config
  copy:
    src: status_config
    dest: "{{ status_dir }}/config"
