- set_fact:
    config_dir: "{{ ansible_facts['env']['HOME'] }}/.config/sway"
    gammastep_dir: "{{ ansible_facts['env']['HOME'] }}/.config/gammastep"

- name: ensure config dir exists
  file:
    path: "{{ config_dir }}"
    state: directory

- name: ensure screenshots dir exists
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/Pictures/screenshots"
    state: directory

- name: install bumblebee-status
  command: pip3 install --user bumblebee-status netifaces
  register: bumblebee_status_install
  changed_when: "'Requirement already satisfied' not in bumblebee_status_install.stdout"

- name: copy config
  template:
    src: config.j2
    dest: "{{ config_dir }}/config"

- name: copy devices config
  copy:
    src: devices.sway
    dest: "{{ config_dir }}/devices.sway"

- name: ensure gammastep dir exists
  file:
    path: "{{ gammastep_dir }}"
    state: directory

- name: copy gammastep ini
  copy:
    src: gammastep.ini
    dest: "{{ gammastep_dir }}/config.ini"

- name: install programs
  package:
    name:
      - gammastep
      - geoclue2
      - wofi
      - sway
      - playerctl
      - brightnessctl
      - grimshot
      - earlyoom
  become: true
  tags: become

# TODO: Doesn't work yet
- name: ensure geoclue conf dir exists
  file:
    path: "/etc/geoclue/conf.d/"
    state: directory
  become: true
  tags: become

- name: allow gammastep access to geoclue
  blockinfile:
    path: /etc/geoclue/conf.d/99-gammastep.conf
    create: true
    block: |
      [gammastep]
      allowed=true
      system=false
      users=
  become: true
  tags: become

- name: tweak oom, systemd-oomd is not doing what it should
  block:
  - name: Install earlyoom
    package:
      name: earlyoom
      state: present

  - name: Disable and stop systemd-oomd
    systemd_service:
      name: systemd-oomd.service
      enabled: false
      state: stopped
      masked: true

  - name: Enable and start earlyoom
    systemd_service:
      name: earlyoom.service
      enabled: true
      state: started

  become: true
  tags: become

- name: tweak, use openh264 instead of noopenh264
  block:
  - name: Install openh264
    package:
      name: openh264
      state: present
  become: true
  tags: become
