- name: Include OS-specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_facts["system"] }}.yml'
      paths:
        - 'vars'
      skip: true

- set_fact:
    config_dir: "{{ ansible_facts['env']['HOME'] }}/.config/fish"

- name: install fish
  package:
    name: fish
    state: present
  become: "{{ ansible_facts['system'] != 'Darwin' }}"

- name: ensure config dir exists
  file:
    path: "{{ config_dir }}"
    state: directory

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
  loop:
    - prompt_help.fish
    - conf.d/dracula.fish
    - conf.d/fzf.fish

- name: copy templates
  template:
    src: config.fish.j2
    dest: "{{ config_dir }}/config.fish"

- name: Add fish to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ fish_shell_path }}"
  become: true
  tags: ['become']

- name: Set fish as default shell
  user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: "{{ fish_shell_path }}"
  become: true
  tags: ['become']
