- name: loop copy
  copy:
    src: "{{ playbook_dir }}/../dot_{{ item }}/"
    dest: "{{ ansible_facts['env']['HOME'] }}/.{{ item }}"
  vars:
    folders:
      - extra
      - config
      - vim
  loop: "{{ folders }}"
