theme = "dracula"

[editor]
bufferline = "multiple"
line-number = "relative"
text-width = 100
soft-wrap = { enable = true }
lsp = { display-inlay-hints = true }

[keys.normal.space]
w = ":w"
q = ":q"

[keys.normal]
C-s = ":w"
A-t = "save_selection"
j = "move_line_down"
k = "move_line_up"
C-h = "goto_previous_buffer"
C-l = "goto_next_buffer"

[keys.normal.g]
j = "move_visual_line_down"
k = "move_visual_line_up"

[keys.insert]
C-c = "normal_mode"
