theme = "dracula"

[editor]
line-number = "relative"
text-width = 100
soft-wrap = { enable = true }
lsp = { display-inlay-hints = true }

[keys.normal.space]
w = ":w"
q = ":q"

[keys.normal]
C-s = ":w"
A-t = "save_selection"

[keys.insert]
C-c = "normal_mode"
